# Getting started with PyTorch tutorial
## What is PyTorch and Why use it?
[PyTorch](https://pytorch.org/) is an open-source machine learning framework based on the Torch library, used for applications such as computer vision and natural language processing.

In [1]:
# if using GPU
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### Import libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


### Creating Tensors
`torch.Tensor()`

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors


In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5701, 0.5631, 0.1880, 0.4195],
        [0.9772, 0.5220, 0.8584, 0.2863],
        [0.7059, 0.4561, 0.2606, 0.4365]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h, w, channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero & Ones

In [18]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dtype is one of the 3 big errors you'll run into with Pytorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_32_tensor.dtype

torch.float16

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, # What device is your tensor on, "cuda"
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [32]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [35]:
# Getting info from tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3101, 0.2948, 0.5075, 0.9327],
        [0.9452, 0.4731, 0.3364, 0.5610],
        [0.9378, 0.4287, 0.8681, 0.6314]])

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3101, 0.2948, 0.5075, 0.9327],
        [0.9452, 0.4731, 0.3364, 0.5610],
        [0.9378, 0.4287, 0.8681, 0.6314]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# Add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 20)

tensor([21, 22, 23])

### Matrix multiplication 

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outher dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [42]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication-dot
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.46 ms, sys: 0 ns, total: 4.46 ms
Wall time: 4.49 ms


In [45]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 82 µs, sys: 11 µs, total: 93 µs
Wall time: 98.9 µs


tensor(14)

In [46]:
tensor @ tensor

tensor(14)

In [47]:
# inner dimensions not match
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
# it gives a shape error

In [48]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.2737, 3.6070, 3.1393],
        [2.3159, 2.6322, 2.3684],
        [3.0879, 3.0081, 2.4251]])

One of the most common errors in deep learning: shape errors

In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of tensors using a transpose. A transpose switches the axes or dimensions of a given tensor.

In [51]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [52]:
# The matrix multiplication operaton works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (smae shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (smae shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [53]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [54]:
# min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [55]:
# max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [56]:
# mean, torch.mean() requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [57]:
# sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [58]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [59]:
# Find the position in tensor that has the minimum value with argmin()
# It returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [60]:
x[0]

tensor(1)

In [61]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
* Squeeze - removes all `l` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute- return a view of the input with dimensions permuted (swapped) in a certain way


In [63]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# adding an extra dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# changing the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
# func. squeeze() removes all single dim.s from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
# func. unsqueeze() adds a single dim. to a target tensor at a specific dim.
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension
x_unsqueezed0 = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed0}")
print(f"New shape: {x_unsqueezed0.shape}")
x_unsqueezed1 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed1}")
print(f"New shape: {x_unsqueezed1.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [70]:
# rearranges the dims of a target tensor in a spesific order
x_org = torch.rand(size=(112, 112, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis order
x_permuted = x_org.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_org.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([112, 112, 3])
New shape: torch.Size([3, 112, 112])


In [71]:
# they share same memory
x_org[0, 0, 0] = 9110
x_org[0, 0, 0], x_permuted[0, 0, 0]

(tensor(9110.), tensor(9110.))