### Running Tensors and PyTorch objects on the GPUs (making faster computations)

Use Google Colab with **changing runtime type** as **GPU**

In [1]:
! nvidia-smi

Sat Sep 24 22:02:57 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Checking for GPU access with PyTorch

In [6]:
import torch
torch.cuda.is_available()

True

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [6]:
# Create a tensor while default on the CPU
import torch
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.to(device))

tensor([1, 2, 3]) tensor([1, 2, 3])


In [11]:
import torch
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the GPU

In [12]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [13]:
# To fix it, first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [14]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')